services:
  notes-bot:
    build: .
    container_name: notes-bot
    volumes:
      - ./:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notes
      - TELEGRAM_BOT_TOKEN=8299540683:AAF9cIRS7LQk-6sAx9VAxvCgg12CdE7eZmU
    depends_on:
      - db
    networks:
      - notes-network

  db:
    image: postgres:latest
    container_name: notes-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notes
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - notes-network

volumes:
  db_data:

networks:
  notes-network: